first_number = int(input('What is the first number? '))
second_number = int(input('What is the second number? '))
print('{:d} + {:d}'.format(first_number, second_number), '= {}'.format(first_number + second_number))
print('{:d} - {:d}'.format(first_number, second_number), '= {}'.format(first_number - second_number))
print('{:d} * {:d}'.format(first_number, second_number), '= {}'.format(first_number * second_number))
print('{:d} / {:d}'.format(first_number, second_number), '= {}'.format(first_number / second_number))
