noun = input('Enter a noun:')
verb = input('Enter a verb:')
adjective = input('Enter an adjective:')
adverb = input('Enter an adverb:')
print('Do you {} your {} {} {}?\nThat\'s hilarious!'.format(verb,adjective,noun,adverb))
